package Pharmacie;

public interface IMedicament {
    public String getNom();
    public void setNom(String nom);
    public String getDosage();
    public void setDosage(String dosage);
    public String getUnite();
    public void setUnite(String unite);
    public String getForme();
    public void setForme(String forme);
    public String getQuantite();
    public void setQuantite(String quantite);
    public double getPrix();
    public void setPrix(String prix);
    public String getOrdonnance();
    public void setOrdonnance(String ordonnance);
    public String getGenerique();
    public void setGenerique(String generique);
    public String getRemboursement();
    public void setRemboursement(String remboursement);
    public String getLaboratoire();
    public void setLaboratoire(String laboratoire);
    public String getStock();
    public void setStock(String stock);
    public String getStockMin();
    public void setStockMin(String stockMin);
    public String getStockMax();
    public void setStockMax(String stockMax);
    public String getStockMoyen();
    public void setStockMoyen(String stockMoyen);
    public String getStockReel();
    public void setStockReel(String stockReel);
    public String getStockTheorique();
    public void setStockTheorique(String stockTheorique);
    public String getStockAlerte();
    public void setStockAlerte(String stockAlerte);
    public String getStockRupture();
    public void setStockRupture(String stockRupture);
    public String getStockCommande();
    public void setStockCommande(String stockCommande);
    public String getStockRecu();
    public void setStockRecu(String stockRecu);
    public String getStockVendu();
    public void setStockVendu(String stockVendu);
    public String getStockPerdu();
    public void setStockPerdu(String stockPerdu);
    public String getStockPrix();
    public void setStockPrix(String stockPrix);
    public String getStockValeur();
    public void setStockValeur(String stockValeur);
    public String getStockValeurTotal();
    public void setStockValeurTotal(String stockValeurTotal);
    public String getStockValeurAchat();
    public void setStockValeurAchat(String stockValeurAchat);
    public String getStockValeurVente();
    public void setStockValeurVente(String stockValeurVente);
}
